version: '3.6'
services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./front/public:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - backend

  flask:
    container_name: flask
    build:
      context: flask/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/code
      - ./celery/app/proj:/code/proj
    environment:
      FLASK_ENV: development
    networks:
      - backend

  celery:
    container_name: celery
    build:
      context: celery/
      dockerfile: Dockerfile
    volumes:
      - ./celery/app:/app
    depends_on:
      - rabbit
    networks:
      - backend

  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3.7.15-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=CT2gNABH8eJ9yVh
    ports:
      - "5672:5672"
    networks:
      - backend

networks:
  backend:
    name: backend
